{
   'language': 'node_js',
   'node_js': '8.7.0',
   'cache': 'yarn',
   'scripts': [
     ' npm run test',
   ],
   'before_install': [
      'cd seasoned_api',
   ],
   'before_script': 'yarn',
   'os': 'osx',
}
