const DISCOVER_DICT = {
  popular_now: "sort_by=popularity.desc&vote_count.gte=200&include_adult=false",
  top_rated: "sort_by=vote_average.desc&vote_count.gte=2000",
  critics_choice:
    "vote_average.gte=8&vote_count.gte=1000&sort_by=vote_average.desc",
  hidden_gems:
    "vote_average.gte=7.5&vote_count.gte=100&vote_count.lte=500&sort_by=vote_average.desc",
  modern_classics:
    "primary_release_date.gte=2020-01-01&vote_average.gte=7.5&vote_count.gte=500&sort_by=vote_average.desc",
  blockbusters: "sort_by=revenue.desc&vote_count.gte=500",
  quick_picks:
    "with_runtime.gte=70&with_runtime.lte=100&vote_average.gte=6.5&vote_count.gte=300&sort_by=vote_average.desc",
  epic_movies:
    "with_runtime.gte=150&vote_average.gte=7&vote_count.gte=500&sort_by=vote_average.desc",
  feel_good:
    "with_genres=35,10751&vote_average.gte=6.5&vote_count.gte=300&sort_by=popularity.desc",
  mind_benders:
    "with_genres=53,9648&vote_average.gte=7&vote_count.gte=500&sort_by=vote_average.desc",
  action_packed:
    "with_genres=28&vote_average.gte=6.5&vote_count.gte=500&sort_by=popularity.desc",
  sci_fi_wonders:
    "with_genres=878&vote_average.gte=6.8&vote_count.gte=400&sort_by=vote_average.desc",
  horror_hits:
    "with_genres=27&vote_average.gte=6.5&vote_count.gte=300&sort_by=popularity.desc",
  romantic_favorites:
    "with_genres=10749&vote_average.gte=6.8&vote_count.gte=300&sort_by=vote_average.desc",
  laugh_out_loud:
    "with_genres=35&vote_average.gte=6.5&vote_count.gte=400&sort_by=vote_average.desc",
  animated_magic:
    "with_genres=16&vote_average.gte=7&vote_count.gte=300&sort_by=vote_average.desc",
  fantasy_worlds:
    "with_genres=14&vote_average.gte=6.5&vote_count.gte=300&sort_by=popularity.desc",
  true_stories:
    "with_genres=99,36&vote_average.gte=7&vote_count.gte=200&sort_by=vote_average.desc",
  crime_dramas:
    "with_genres=80,9648&vote_average.gte=7&vote_count.gte=400&sort_by=vote_average.desc",
  war_epics:
    "with_genres=10752&vote_average.gte=7&vote_count.gte=300&sort_by=vote_average.desc",
  westerns:
    "with_genres=37&vote_average.gte=6.5&vote_count.gte=200&sort_by=vote_average.desc",
  family_night:
    "with_genres=10751&vote_average.gte=6.5&vote_count.gte=300&sort_by=popularity.desc",
  international_cinema:
    "with_original_language=fr|es|de|ja|ko|it&vote_average.gte=7&vote_count.gte=200&sort_by=vote_average.desc",
  "90s_nostalgia":
    "primary_release_date.gte=1990-01-01&primary_release_date.lte=1999-12-31&vote_average.gte=6.5&vote_count.gte=500&sort_by=popularity.desc",
  "2000s_classics":
    "primary_release_date.gte=2000-01-01&primary_release_date.lte=2009-12-31&vote_average.gte=6.8&vote_count.gte=500&sort_by=vote_average.desc",
  "2010s_best":
    "primary_release_date.gte=2010-01-01&primary_release_date.lte=2019-12-31&vote_average.gte=7&vote_count.gte=500&sort_by=vote_average.desc",
  golden_age:
    "primary_release_date.lte=1979-12-31&vote_average.gte=7.5&vote_count.gte=300&sort_by=vote_average.desc",
  recent_releases:
    "primary_release_date.gte=2025-01-01&vote_count.gte=50&sort_by=popularity.desc",
  crowd_pleasers:
    "vote_count.gte=3000&vote_average.gte=7&sort_by=vote_count.desc",
  indie_darlings:
    "vote_average.gte=7.5&vote_count.gte=150&vote_count.lte=800&without_genres=28,12,14,878&sort_by=vote_average.desc",
  thriller_edge:
    "with_genres=53&vote_average.gte=7&vote_count.gte=500&sort_by=vote_average.desc",
  dark_comedy:
    "with_genres=35,80&vote_average.gte=6.8&vote_count.gte=300&sort_by=vote_average.desc",
  musical_magic:
    "with_genres=10402&vote_average.gte=6.5&vote_count.gte=200&sort_by=vote_average.desc",
  space_odyssey:
    "with_genres=878&with_keywords=9663,10683&vote_average.gte=6.5&vote_count.gte=200&sort_by=popularity.desc",
  superhero_saga:
    "with_genres=28,12,14&with_keywords=9715,180547&vote_average.gte=6.5&vote_count.gte=500&sort_by=popularity.desc",
  oscar_winners:
    "vote_average.gte=7.5&vote_count.gte=1500&sort_by=vote_average.desc",
  coming_of_age:
    "with_genres=18&with_keywords=4344&vote_average.gte=6.8&vote_count.gte=200&sort_by=vote_average.desc",
  heist_films:
    "with_genres=80,53&with_keywords=157186&vote_average.gte=6.5&vote_count.gte=300&sort_by=vote_average.desc",
  zombies_apocalypse:
    "with_genres=27&with_keywords=12377&vote_average.gte=6&vote_count.gte=200&sort_by=popularity.desc",
  time_travel:
    "with_keywords=4379&vote_average.gte=6.5&vote_count.gte=300&sort_by=vote_average.desc"
};

export default DISCOVER_DICT;
